#$ 数据存放路径
data_path: /media/g/T100  #相对路径: ./  #相对路径:建议设置到外置固态移动硬盘上
#$ 滤波方式
local_map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter
display_filter: voxel_filter # rviz 实时显示点云时滤波方法，目前支持：voxel_filter
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter

#$$ voxel_filter滤波器
voxel_filter:
    local_map:
        leaf_size: [0.6,0.6,0.6]
    frame:
        leaf_size: [1.3,1.3,1.3]
    display:
        leaf_size: [0.5,0.5,0.5]
    

#$ 匹配方式 
registration_method: NDT   # ICP SICP等方式可选择

#$$ NDT参数配置
NDT:
    res: 1.0
    step_size: 0.1
    trans_eps: 0.01 
    max_iter: 30

#$ 局部地图参数
key_frame_distance: 2.0
local_frame_num: 20 












